services:
  runner:
    container_name: ${RUNNER_NAME:-gitlab-runner}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config:/etc/gitlab-runner
    image: ${RUNNER_IMAGE:-gitlab/gitlab-runner}:${RUNNER_TAG:-latest}
    environment:
      TZ: ${RUNNER_TZ:-Europe/Paris}

  app:
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
#    image: lucy135/qfqq
    ports:
      - "1001:80"

  database:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - network

  api:
    container_name: api
    build:
      context: api
      dockerfile: api/Dockerfile
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DB_NAME=${DB_NAME:-5432}
      - DATABASE_URL=postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@database:${DB_NAME:-5432}/${DB_NAME:-db}?serverVersion=16&charset=utf8"
      - COMPOSER_ALLOW_SUPERUSER=1
      - CORS_ALLOW_ORIGIN=${DOMAIN_NAME:-localhost}
      - CORS_ALLOW_ORIGIN=${DOMAIN_NAME:-localhost}
    volumes:
      - ./api:/var/www/html
      - ./tests:/var/www/html/tests
      - ./api/vendor:/var/www/html/vendor
      - ./scripts:/var/www/scripts
    networks:
      - network
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: frontend/Dockerfile
      target: ${APP_ENV:-dev}
      args:
        DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    environment:
      CHOKIDAR_USEPOLLING: true
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    ports:
      - "80"
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./api:/var/www/html
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    networks:
      - network
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  network:
    driver: bridge